version: "3.8"
services: 
    postgres:
        container_name: postgres
        image: postgres
        ports: 
            - 5432:5432
        environment: 
            POSTGRES_PASSWORD: 95283
            POSTGRES_USER: postgres
            POSTGRES_DB: fanfictions
        restart: always
        volumes: 
            - pgdata:/var/lib/postgresql/data
    web:
        container_name: web
        build: .
        ports: 
            - 8080:8080
        depends_on: 
            - postgres
volumes: 
    pgdata: